### PR TITLE
zphysics: DebugRenderer implemented.

### PR DESCRIPTION
**Pull request by a-day-old-bagel**
Tests are included, all seems to pass tests.
Comments are included where I thought something needed explaining.
I wanted to write a sample for it to include in samples, and I might do that later still if nobody else does.

### CODE REVIEW

**Comment by a-day-old-bagel** [comment]
@michal-z If there's anything you'd like me to change about the design, I'm open to doing it. I have found a few things to edit, which I'll push to a second commit here in a bit.

If it's a pain to look through it or test it right now, I can provide more details about the tests I ran.

**Comment by michal-z** [comment]
This looks good, many thanks and sorry for the delay, I should merge it tomorrow.

**Comment by a-day-old-bagel** [comment]
Just added some helper decls

**Comment by michal-z** [comment]
Great work!

**Pull request merged**
