### PR TITLE
Add basic ImPlot functions

### PR DESCRIPTION
**Pull request by ckrowland**
For ImPlot::PlotLine and ImPlot::PlotBar I force a numeric type for the values, but the ImPlot function is generic

### CODE REVIEW

**Comment by michal-z** [comment]
Thanks for the PR!

It will require some work before I can merge it. Do you want to clean it up a bit? I can do it if you want.

**Comment by ckrowland** [comment]
Clean it up? Like the formatting or the function calls? I'm not sure what you have in mind.

**Comment by michal-z** [comment]
There are few things:
- Hardcoded constants in: `zguiSetupLegend`, `zguiSetupLegend`, `zguiSetupAxes`
- Generally `zgui` passes args in structs which allows us to provide default values - we should follow this convention
- I think we need to to prefix ImPlot functions with `zguip` (or something) to avoid name clashes (for example,  there is ImGui::PushStyleColor() and ImPlot::PushStyleColor())

**Comment by ckrowland** [comment]
Ok, yes thanks for the clarification. I can do that sometime this week.

**Comment by michal-z** [comment]
Sure, no rush.

**Comment by michal-z** [comment]
Looks good, thanks! Will merge it today.

**Pull request merged**
