### PR TITLE
zjobs: Remove use of thread sleep 

### PR DESCRIPTION
**Pull request by Avokadoen**
Related issues: #130, #175

cc @garettbass

### CODE REVIEW

**Comment by Avokadoen** [comment]
There is also this WIP branch by @garettbass 
https://github.com/garettbass/zig-gamedev/tree/garett/zjobs-idle-queue 

It might be a better approach. I think changing the primitive to ResetEvent in the queue and then the current flow:

1. If jobid's entry index is not the current jobid then we don't check event (basically status quo)
2. If Entry is idle/empty then the event is set
3. If the Entry is executing jobid then it's reset

**Comment by Avokadoen** [comment]
I tried adding `ResetEvent` to the Slot struct and then implement `wait(prereq: JobId)` with the following impl (based on isPending):

```zig
       /// Waits until the specified `prereq` is completed.
        pub fn wait(self: *Self, prereq: JobId) void {
            if (prereq == JobId.none) return;

            const _id = prereq.fields();
            assert(isLiveCycle(_id.cycle));

            const slot: *Slot = &self._slots[_id.index];
            const slot_cycle = slot.cycle.load(.Monotonic);

            if (slot_cycle == _id.cycle) {
                slot.idle_event.wait();
            }
        }
   ```
   
   We then just do the following in the top of executeJob in Slot: 
   
```zig
// while executing any observer can wait on the idle event
self.idle_event.reset();
defer self.idle_event.set();
```

The problem is that I hit deadlocks in the the "combine jobs respect prereq" test. 
It seems like a the wait is the cause of the deadlock

```zig
       /// Waits until the specified `prereq` is completed.
        pub fn wait(self: *Self, prereq: JobId) void {
            // ...
            const slot_cycle = slot.cycle.load(.Monotonic);
            
            // RC: slot_cycle might not be the active slot_cycle when we compare and when we call wait
            if (slot_cycle == _id.cycle) { 
                slot.idle_event.wait();
            }
        }
```

I might be able to resolve the deadlock by adding a mutex to the slots (which means a condition might be a better fit) :thinking:

**Comment by Avokadoen** [comment]
I have a working version with the mutex + condition wrapping any write/read of the slot with mutex. I'll profile vs main branch to see if there are gains from this and if cpu active improves. I can't run the throughput test as it seems to be crashing on my   i7-6500U 

I also want to make it so the enqueue only wakes a single thread instead of all threads

**Comment by Avokadoen** [comment]
Blocking individual threads have proven to be a challenge :sweat_smile: 
I think it should be fine to open a issue on that instead of trying to solve that in this PR.

I am currently traveling and I have issues with my laptop so this PR won't be marked as ready until I come back on Sunday and have the opportunity to benchmark this patch.

**Comment by Avokadoen** [comment]
@garettbass I'm marking this as ready for review. Overall it seems like this actually might cause minor regression in some scenarios. I ran throughput which is aprox 10ms slower on i7 6700k (~310ms to ~320ms). I also have a [game of life example in ecez](https://github.com/Avokadoen/ecez/blob/main/examples/game-of-life/main.zig) which does not show either regression or improvements although there is no long running jobs in either. I think we would see less CPU active in longer running jobs, especially if we could get threads to individually wake up when scheduling new work.

**Comment by Avokadoen** [comment]
For reference this is the results of the game of life example running for ~34s where there is some improvement with the PR patches:

- 34.06s vs 38.89s total time spent on waiting
- min cpu util of 68.75% vs 79.17%

image

**Comment by garettbass** [comment]
I did some work on waking threads using condition variables last year, but never completed the refactor.  I have no objection to these changes and likely will not be involved in further development of this library in the near future.

**Comment by Avokadoen** [comment]
Thanks for the heads up and all the amazing work you have done so far @garettbass! ❤️

**Pull request merged**
